### ISSUE TITLE
Specify Node.js and pnpm versions in package.json

### ISSUE THREAD

**Issue by anonymousRecords** [ruucm/shadergradient#102]
To enhance consistency across development environments, 
we might consider specifying the recommended `Node.js` and `pnpm` versions in our package.json file. 
One way to achieve this could be through the use of the [engines field](https://pnpm.io/package_json#engines).
What do you think about this approach?

Proposed changes to root package.json:

```json
{
  ...
  "packageManager": "pnpm@8.14.0",
  "engines": {
    "node": ">=14.0.0",
    "pnpm": "^8.14.0"
  },
  "version": "0.0.1"
 ...
}

**Comment by ruucm** [comment]
PR please :)
