### ISSUE TITLE
How to i change camera angle?

### ISSUE THREAD

**Issue by destiny0114** [ruucm/shadergradient#104]
how do i adjust cAzimuthAngle and cPolarAngle because is not workng.
![2254f904-a8d7-4e7d-9851-f07202852137](https://github.com/user-attachments/assets/b11a802d-8a58-43cc-8fd0-4e66f42bb860)
![SCR-20241004-pkgp](https://github.com/user-attachments/assets/088634a1-3134-4a2b-9a1a-564cfa3ea867)

**Comment by ruucm** [comment]
Could you share your issue with a codesandbox link?

it looks workin on my side.

https://codesandbox.io/p/devbox/optimistic-roentgen-fwxv4x

**Comment by destiny0114** [comment]
i fixed by using ShaderGradientCanvas. Your example not working even i added cPolarAngle.

**Comment by itsbppradhan** [comment]
However upon launching the nextjs app router sample sandbox and resizing the webpage (yes the webpage), the camera pos resets suddenly.

I tried using the shader gradient and shader canvas as recommended in Readme canvas in a new next.js project but in vain for I this time got not but 2 broken gradients side by side

**Comment by anonymousRecords** [comment]
@itsbppradhan 
> However upon launching the nextjs app router sample sandbox and resizing the webpage (yes the webpage), the camera pos resets suddenly.
> 
> I tried using the shader gradient and shader canvas as recommended in Readme canvas in a new next.js project but in vain for I this time got not but 2 broken gradients side by side

Thank you for reporting this issue. To help us better understand and resolve the problem, could you please provide:

- More specific code snippets showing how you're using the ShaderGradient and ShaderGradientCanvas components
- Any error messages or console logs related to the issue

This additional information will greatly help in diagnosing and fixing the problem. Thanks for your cooperation!

**Comment by itsbppradhan** [comment]
I have encountered several issues with the original Next.js template using the app router. Specifically, the object resets to its original size when the window is resized (please refer to video 1).
https://drive.google.com/file/d/1tvdYB7NuH2N8hWLSYl4n3GpGikjo_xVB/view?usp=sharing

After downloading the code and making modifications to achieve a full-screen display, the problem persisted (see video 2).
https://drive.google.com/file/d/1471Cq4PaHrpBnGVTgSS6ID5OYxqi-V92/view?usp=sharing

Additionally, I created a new next.js app and implemented the shader canvas method as described in the README.md file and placed it within a screen-sized div. However, this resulted in broken colors, and when scrolling the mouse over the gradient, the size changes unexpectedly. Surprisingly, there are two instances for no apparent reason (video 3).
https://drive.google.com/file/d/1CwH7NJBi7SMt4dlYSzoBMPzxVWZueVw2/view?usp=sharing

I would appreciate any assistance or guidance you can provide to resolve these issues.

Thank you for your time and support.

**Comment by destiny0114** [comment]
@itsbppradhan this is the way I use shadergradient u can tweak the settings.
`import { ShaderGradientCanvas, ShaderGradient } from 'shadergradient';
import * as reactSpring from '@react-spring/three';
import * as drei from '@react-three/drei';
import * as fiber from '@react-three/fiber';

export const CanvasShaderGradient = () => {
  return (
    <ShaderGradientCanvas
      importedFiber={{ ...fiber, ...drei, ...reactSpring }}
      style={{
        position: 'absolute',
        top: 0,
        width: '100vw',
        height: '100vh',
        pointerEvents: 'none',
      }}
      pixelDensity={1}
      fov={40}
    >
      <ShaderGradient
        type="waterPlane"
        color1="#ff7300"
        color2="#b03182"
        color3="#b03182"
        frameRate={10}
        cameraZoom={1}
        brightness={1.2 * Math.PI}
        lightType="3d"
        envPreset="city"
        cDistance={3.9}
        cAzimuthAngle={180}
        cPolarAngle={115}
        range="disabled"
        uAmplitude={0}
        uDensity={1.1}
        uFrequency={5.5}
        uStrength={2.4}
        uSpeed={0.1}
        uTime={0.2}
        grain="off"
        reflection={0.1}
        positionX={-1}
        positionZ={-1}
        rotationZ={235}
        enableTransition={false}
      />
    </ShaderGradientCanvas>
  );
};`

**Comment by itsbppradhan** [comment]
Did you use the example or scaffolded a new Next.js project?

**Comment by itsbppradhan** [comment]
![image](https://github.com/user-attachments/assets/0fc52cf2-9846-421d-8529-9ed74cbb9145)
Is the colour scheme majestic

**Comment by destiny0114** [comment]
@itsbppradhan I think so because we've been same case using their example not working

**Comment by itsbppradhan** [comment]
`{
  "name": "lounge",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@react-three/fiber": "^8.17.10",
    "framer-motion": "^11.11.9",
    "next": "14.2.15",
    "react": "^18",
    "react-dom": "^18",
    "shadergradient": "^1.2.14",
    "three": "^0.169.0"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "@types/three": "^0.169.0",
    "eslint": "^8",
    "eslint-config-next": "14.2.15",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "typescript": "^5"
  }
}
`

this is my package.json in my new next.js app which works without any three-mesh-bvh error

**Comment by ruucm** [comment]
This one looks like resolved.

Also I've added an example of using `cAzimuthAngle`, `cPolarAngle` props at `apps/example-nextjs-dev/app/page.tsx`

Closing.
