### ISSUE TITLE
dampingFactor deprecated

### ISSUE THREAD

**Issue by simonghs** [ruucm/shadergradient#111]
I have been using shadergradient for a while now. For the implementation I had followed your guide here on github, however now out of nowhere it gives me problems with dampingFactor and this does not allow me to use the library.
I am using next 14 (pages router), do you have any advice? I see that you are using data-camera-controls-version=“2.9.0” is there any possibility to downgrade?

<img width="619" alt="Screenshot 2024-11-07 alle 15 21 11" src="https://github.com/user-attachments/assets/87f13d9f-b0e7-4661-801a-8b6b593f6c82">

**Comment by ruucm** [comment]
Thanks for letting me know.

Updated to smoothTime from v2.0.2

https://github.com/ruucm/shadergradient/commit/1cf0d70a2a63e635e4dae1cd0dc8e711a7f23793
