### ISSUE TITLE
Unable to use shadergradient in CRA app

### ISSUE THREAD

**Issue by RonithK** [ruucm/shadergradient#59]
Using the following code snippet results in an error that says "LCanvas" couldn't be resolved.

```JSX
import React from 'react'
import { LCanvas, Gradient } from 'shadergradient'
import * as reactSpring from '@react-spring/three'
import * as drei from '@react-three/drei'
import * as fiber from '@react-three/fiber'

function App() {
  return (
    <LCanvas
      importedFiber={{ ...fiber, ...drei, ...reactSpring }}
      style={{
        position: 'absolute',
        top: 0,
      }}
    >
      <Gradient cDistance={32} cPolarAngle={125} />
    </LCanvas>
  )
}
```

I tried using this code snippet instead (based on the example CRA app in the code sandbox):
```
import "./App.css";
import { GradientCanvas, Gradient } from "shadergradient";

function App() {
    return (
        <div className="App">
            <GradientCanvas style={{ position: "absolute" }}>
                <Gradient
                    cDistance={32}
                    cPolarAngle={125}
                    color1="#ff5005"
                    color2="#dbba95"
                    color3="#d0bce1"
                />
            </GradientCanvas>
        </div>
    );
}

export default App;
```

But this results in the following run time error:
<img width="890" alt="CleanShot 2023-10-07 at 22 56 20@2x" src="https://github.com/ruucm/shadergradient/assets/46459079/4446764d-d67f-4fbe-b6b7-85acc5ba0262">

How do we get shadergradients working properly in a react app?

**Comment by ruucm** [comment]
Hey thanks for reporting this.

I've updated code examples you can follow it now (from the v1.2.2). 

Behind of this, we've decided to detach store codes and changed main component names to "ShaderGradient" from "Gradient". (but was not applied to examples)



Here are examples using it.

[CRA Example](https://codesandbox.io/p/sandbox/github/ruucm/shadergradient/tree/main/apps/example-cra?file=%2Fsrc%2FApp.tsx)

[Next.js Example](https://codesandbox.io/p/sandbox/zjxeci?file=%2Fsrc%2Fpages%2Findex.tsx)


Let me know if it still happens!
