### ISSUE TITLE
Three.JS Version Incompatibility

### ISSUE THREAD

**Issue by Jonas-Lieske** [ruucm/shadergradient#61]
Thank you for this neat looking package!
While testing out the example from the README for my React page, I have encountered a problem where the component was not being displayed and found the problem to be the Three.JS version.

For context, this is the example I tested:
```
import React from 'react'
import { ShaderGradientCanvas, ShaderGradient } from 'shadergradient'
import * as reactSpring from '@react-spring/three'
import * as drei from '@react-three/drei'
import * as fiber from '@react-three/fiber'

function App() {
  return (
    <ShaderGradientCanvas
      importedFiber={{ ...fiber, ...drei, ...reactSpring }}
      style={{
        position: 'absolute',
        top: 0,
      }}
    >
      <ShaderGradient
        control='query'
        urlString='https://www.shadergradient.co/customize?animate=on&axesHelper=off&bgColor1=%23000000&bgColor2=%23000000&brightness=1.2&cAzimuthAngle=180&cDistance=3.6&cPolarAngle=90&cameraZoom=1&color1=%2352ff89&color2=%23dbba95&color3=%23d0bce1&embedMode=off&envPreset=city&fov=45&gizmoHelper=hide&grain=on&lightType=3d&pixelDensity=1&positionX=-1.4&positionY=0&positionZ=0&reflection=0.1&rotationX=0&rotationY=10&rotationZ=0&shader=defaults&type=plane&uDensity=1.3&uFrequency=5.5&uSpeed=0.4&uStrength=4&uTime=0&wireframe=false&zoomOut=false'
      />
    </ShaderGradientCanvas>
  )
}
```

I have encountered the following error that is being printed multiple times a second:
```
Uncaught Error: Can not resolve #include <uv2_pars_vertex>
    at includeReplacer (three.module.js:18944:1)
    at String.replace (<anonymous>)
    at resolveIncludes (three.module.js:18934:1)
    at WebGLProgram (three.module.js:19460:1)
    at Object.acquireProgram (three.module.js:20338:1)
    at getProgram (three.module.js:28886:1)
    at setProgram (three.module.js:29092:1)
    at WebGLRenderer.renderBufferDirect (three.module.js:28156:1)
    at renderObject (three.module.js:28823:1)
    at renderObjects (three.module.js:28792:1)
```

After some digging, I discovered that these errors stem from the recent updates in version [0.151.0](https://github.com/mrdoob/three.js/releases/tag/r151) and above of three.js. When I downgrade to version 0.150.0, everything works smoothly on my end.

From what I can see each new version of Three.js seems to come with its own migration guide, so this could potentially be a recurring issue. 
I would suggest setting up the peerDependencies to avoid this problem in the future.

**Comment by ruucm** [comment]
Thanks to checking this @Jonas-Lieske.

Added.

https://github.com/ruucm/shadergradient/commit/5cb541fa22879713da3ddd077504440bd83614ba
