### ISSUE TITLE
How to remove the rotation-like animation when the page loads

### ISSUE THREAD

**Issue by evtol** [ruucm/shadergradient#68]
Does the library support the removal of the initial rotation-like animation when the page refreshes? 
I am using the library in a Nextjs project. 

I have attached a gif of the animation i am referring to below (it is taken from the Next.js Starter code sandbox): 
![animation](https://github.com/ruucm/shadergradient/assets/742897/876cd622-c29c-4202-bfbe-282cf1afc964)

**Comment by evtol** [comment]
Setting cAzimuthAngle={0} fixed my issue.

**Comment by Kinark** [comment]
it didn't for me

**Comment by theta-scholes** [comment]
it fixed it but now it doesnt look as cool. The angle made it look like waves, without it looks like abstract art
