### ISSUE TITLE
Black flash on load

### ISSUE THREAD

**Issue by jordanliu** [ruucm/shadergradient#72]
Is there any way the black flash before loading the shader be prevented? or any suggestions on how this can look less harsh/evident?

**Comment by appinteractive** [comment]
@jordanliu were you successful in removing the initial animation?

**Comment by ruucm** [comment]
could you share more details about your case? Some loadings are needed when you need to use specific HDR dependent shader like Interstella (not others much).

**Comment by ruucm** [comment]
@appinteractive I added `enableTransition` prop to disable the initial animation. (from v1.2.9)
