### ISSUE TITLE
Blanc/Empty Frame  in "Framer"

### ISSUE THREAD

**Issue by ALXRITR** [ruucm/shadergradient#76]
I just dont get it.
When i Remix the Project in Framer, she Shader is working.

As son as i copy it into my Project OR copy anything from my Project inside the Remix, close & reopen the Project again, the Shader is blanc.

i first thought its anything special from my Project that could cause this, so i tried to copy everything from my project one by one.
as soon as i copy any component from my projects the shader stops working.

does anyone have an idea?

**Comment by ruucm** [comment]
It might have conflicts with components existing in your project. Please copy it to new clean projects.
