### ISSUE TITLE
Unable to implement in Next.js

### ISSUE THREAD

**Issue by RainyNight9** [ruucm/shadergradient#77]
Seems like it can only be used in CSR? But setting 'use client' did not succeed?
Can you give an example? Using Next.js https://nextjs.org/docs/getting-started/installation
Looking forward to it!

**Comment by ruucm** [comment]
Hello here are Next.js examples

Next.js Starter (App Router): [CodeSandbox](https://codesandbox.io/p/sandbox/github/ruucm/shadergradient/tree/main/apps/example-nextjs-approuter)
Next.js Starter: [CodeSandbox](https://codesandbox.io/p/sandbox/github/ruucm/shadergradient/tree/main/apps/example-nextjs)
