### ISSUE TITLE
How to support responsiveness?

### ISSUE THREAD

**Issue by RainyNight9** [ruucm/shadergradient#79]
How to support responsiveness?
Explanation: How to do it? Is there support for parameters or methods? The legend can be kept displayed normally as the width and height of the screen change.

**Comment by RainyNight9** [comment]
![image](https://github.com/ruucm/shadergradient/assets/20129035/e38ab388-0f37-4618-9ca0-633324746d07)

**Comment by ruucm** [comment]
The legend? what do you mean.

**Comment by RainyNight9** [comment]
sorry, It has been resolved。
