### ISSUE TITLE
gradient not in correct place issue

### ISSUE THREAD

**Issue by adityamandal-Developer** [ruucm/shadergradient#84]
in initial load or refresh the page is like this 
![Screenshot 2024-06-10 151311](https://github.com/ruucm/shadergradient/assets/112809321/d0667047-2fd7-41a1-b057-4efc525a6c9f)

and if I resize the window then its coming up correctly
![Screenshot 2024-06-10 151604](https://github.com/ruucm/shadergradient/assets/112809321/947ec139-02cf-490d-ba46-d91d8e700b60)

the code is same, this is from 
https://github.com/ruucm/shadergradient/tree/main/apps/example-nextjs-approuter

**Comment by adityamandal-Developer** [comment]
anyone know how to fix this issue

**Comment by ruucm** [comment]
You can change gradient's position with many props.

Try it https://www.shadergradient.co/customize.

<img width="1238" alt="Screenshot 2024-06-16 at 12 02 48 PM" src="https://github.com/ruucm/shadergradient/assets/33462905/77cb4027-b93d-4927-b8db-b579e99b7f3c">
