### ISSUE TITLE
Change values with transition

### ISSUE THREAD

**Issue by simonghs** [ruucm/shadergradient#86]
Hello everyone, I'm implementing shadergradient in React, but I have a problem: when I change a parameter (like uStrength) after an interaction, the change happens abruptly.

Is there a way to make this transition smooth? I've also tried incrementing the value every 10ms but the result is not optimal.

**Comment by ruucm** [comment]
Transitions are currently possible for  only a few params now. (camera related, position, rotation)

I used `camera-control` & `@react-spring/three` for these transitions, but I haven't implemented transitions for values directly related to shader codes.
