### ISSUE TITLE
How to disable camera controls

### ISSUE THREAD

**Issue by willscottrod** [ruucm/shadergradient#87]
Hi, I'm trying to disable camera controls when the shader gradeient isn't full screen. 

Is there a way to do this on the canvas or shader gradient element?

**Comment by chloelavrat** [comment]
Hi,

You can disable camera controls by setting the pointer events to `none` on the canvas element. Add the following to your `ShaderGradientCanvas`:

```jsx
<ShaderGradientCanvas
  importedFiber={{ ...fiber, ...drei, ...reactSpring }}
  onCreated={({ gl }) => {
    gl.domElement.style.pointerEvents = 'none';  // Disable interactions
  }}
>
  <ShaderGradient
    // Your gradient configuration here
  />
</ShaderGradientCanvas>
```

This will disable user interactions with the shader gradient. 
I hope this helps 😃

**Comment by willscottrod** [comment]
Thank you so much! I was so lost trying to figure out the props within the custom canvas wrapper.

This works perfectly.
