### ISSUE TITLE
set initial rotation

### ISSUE THREAD

**Issue by TheMikeyRoss** [ruucm/shadergradient#95]
When the gradient first loads, it seems to be in a wrong orientation and then it orients itself. But it doesn't feel or look good when that happenes. is there anyway  I can prevent that? maybe load it with an initial orientaiton so that it doesn't have to orient itself?

This happens everytime i refresh the page, or visit the page for the first time

![gradient-shader-issue](https://github.com/user-attachments/assets/0e8d13ae-13b6-4f48-96eb-0f738a46ab6e)

**Comment by tappypuppy** [comment]
I've seen this and fixed it.
[https://github.com/ruucm/shadergradient/issues/68](url)

**Comment by tappypuppy** [comment]
#68 How to remove the rotation-like animation when the page loads

I've seen this and fixed it.

**Comment by ruucm** [comment]
Have you tried to use `enableTransition` prop?

**Comment by TheMikeyRoss** [comment]
> Have you tried to use enableTransition prop?

Yup that fixed it, thanks 👍
